name: Build and Push Docker Image

on: 
  push: 
    branches: [main]
  workflow_dispatch: # manual button to test

env: 
  DOCKER_IMAGE: portfolio

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
       # ==================== BUILD ====================
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest \
                     ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
       
        # ==================== PUSH ====================
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          echo "user: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}"

        # ==================== DEPLOY ==================
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy to EC2
        run: |
          DOCKER_USER="${{ secrets.DOCKER_USERNAME }}"
          DOCKER_IMG="${{ env.DOCKER_IMAGE }}"
          EC2_HOST="${{ secrets.EC2_HOST }}"
          EC2_USER="${{ secrets.EC2_USER }}"
          
          echo "Deploying $DOCKER_USER/$DOCKER_IMG:latest to $EC2_HOST"
          
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              $EC2_USER@$EC2_HOST bash << EOF
            echo "🚀 Starting deployment..."
            
            docker pull $DOCKER_USER/$DOCKER_IMG:latest
            
            docker stop portfolio 2>/dev/null || true
            docker rm portfolio 2>/dev/null || true
            
            docker run -d \
              --name portfolio \
              --restart unless-stopped \
              --memory="400m" \
              --cpus="0.5" \
              -p 8080:80 \
              $DOCKER_USER/$DOCKER_IMG:latest
            
            docker image prune -af
            
            echo "✅ Deployment complete!"
            docker ps | grep portfolio
          EOF
      # ==================== SUMMARY ====================
      - name: Deployment Summary
        run: |
          echo " Deployment completed successfully!"
          echo " Image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
          echo " Site: http://${{ secrets.EC2_HOST }}"
          echo " SSH: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}"
